name: "Check formatting"
on:
  pull_request:
  push:
jobs:
  fernglas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: canidae-solutions/lix-quick-install-action@v3
    - run: 'nix shell .#cargo .#rustfmt -c cargo fmt --check'
  nibbletree:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: canidae-solutions/lix-quick-install-action@v3
    - run: 'nix shell .#cargo .#rustfmt -c cargo fmt --manifest-path nibbletree/Cargo.toml --check'
