name: "Check formatting"
on:
  pull_request:
  push:
jobs:
  fernglas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - run: 'nix shell .#cargo .#rustfmt -c cargo fmt --check'
  nibbletree:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - run: 'nix shell .#cargo .#rustfmt -c cargo fmt --manifest-path nibbletree/Cargo.toml --check'
